// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simple_ETL_Project.Database;

#nullable disable

namespace Simple_ETL_Project.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Simple_ETL_Project.Database.Entities.TripData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoLocationId")
                        .HasColumnType("int")
                        .HasColumnName("do_location_id");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fare_amount");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int")
                        .HasColumnName("passenger_count");

                    b.Property<int>("PuLocationId")
                        .HasColumnType("int")
                        .HasColumnName("pu_location_id");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("store_and_fwd_flag");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tip_amount");

                    b.Property<DateTime>("TrepDropOffDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("trep_drop_off_date_time");

                    b.Property<DateTime>("TrepPickUpDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("trep_pick_up_date_time");

                    b.Property<double>("TripDistance")
                        .HasColumnType("float")
                        .HasColumnName("trip_distance");

                    b.HasKey("Id")
                        .HasName("pk_trip_datas");

                    b.ToTable("trip_datas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
